apiVersion: apps/v1
kind: Deployment
metadata: 
    name: order
    labels:
        app: order-app
        type: order-backend
spec: 
    replicas: 1
    selector: 
        matchLabels:
            app: order-pod-app
            type: order-backend-pod
    template: 
        metadata: 
            name: order-pod
            labels:  
                app: order-pod-app
                type: order-backend-pod
        spec: 
             containers:
                  - name: order-pod
                    image: pandeych009/itlogiclab-restaurant-order:1.0.1
                    imagePullPolicy: IfNotPresent
                    resources:   
                        limits: 
                            memory: "512Mi"
                            cpu: "0.6"                                 
                        requests:
                            memory: "256Mi"
                            cpu: "0.5"            
                    env:
                      - name: SPRING_DATASOURCE_URL
                        value: 'jdbc:mariadb://mysql-order-service:3306/orderdb'
                        #valueFrom: 
                         # secretKeyRef: 
                          #    name: mysql-db-url
                           #   key:  order-url
                      - name: SPRING_DATASOURCE_USERNAME
                        valueFrom: 
                          secretKeyRef: 
                              name: restaurant-app-secret
                              key:  username
                      - name: SPRING_DATASOURCE_PASSWORD
                        valueFrom: 
                           secretKeyRef: 
                               name: restaurant-app-secret
                               key: password
                      - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
                        value: org.mariadb.jdbc.Driver                                            
                                                                           
                    ports: 
                       - name: httpport
                         containerPort: 20001 
                         protocol:  TCP
---
apiVersion: v1
kind: Service
metadata: 
    name: order-service
spec: 
    selector: 
        app: order-pod-app
        type: order-backend-pod
    type: NodePort                      
    ports: 
        - targetPort: 8080
          port: 20001
          nodePort: 30002
    clusterIP: 10.101.102.102
    