apiVersion: v1
kind: Secret
metadata: 
  name: mysql-db-url
data: 
   order-url: amRiYzptYXJpYWRiOi8vbXlzcWwtc2VydmljZS1vcmRlcjozMzA2L29yZGVyZGI/dXNlU1NMPWZhbHNlJm1heF9hbGxvd2VkX3BhY2tldD0xNTcyODY0MAo=
   order-database: b3JkZXJkYgo= ##orderdb