apiVersion: v1 
kind: Pod
metadata:
  name: order-pod
  namespace: practice 
  labels: 
     app: order
     type: backend 
spec: 
  containers: 
    - name: order-container
      image: pandeych009/itlogiclab-restaurant-order:2.0.2
      imagePullPolicy: IfNotPresent
      resources: 
        requests: 
          memory: "128Mi"
          cpu: "0.5"
        limits:
           memory: "256Mi"
           cpu: "0.8"
      ports: 
        - name: http
          protocol: TCP
          containerPort: 20010 ##PORT OF POD

      env: 
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql-order-service:3306/orderdb?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false"
        - name: SPRING_DATASOURCE_USERNAME
          value: cpandey
        - name: SPRING_DATASOURCE_PASSWORD
          value: chandan@1234

---
apiVersion: v1
kind: Service
metadata: 
   name: order-service
   labels:
      app: order-service 
      type: service
spec: 
   selector: 
       app: order 
   type: NodePort
   ports: 
     - targetPort: 20010 ## PORT of POD
       nodePort: 30000 ## PORT of Node where application is availble 30000 - 32767
       port: 80 ## Port of Service 
  ## clusterIP:  