apiVersion: v1
kind: Service
metadata: 
  name: jekyll
  namespace: development
  labels: 
    app: jekyll
    type: jekyll-svc
spec: 
   type: 
   selector: 
   ports: 
     - targetPort: 4000
       port: 8080
       nodePort: 30097  