apiVersion: v1
kind: PersistenceVolume
metadata: 
   name: pv-challange
spec: 
  capacity: 
    storage: "1Gi"
  storageClassName: standard ##
  accessModes: 
     - ReadWriteOnce  ##ReadWriteOnce, ReadWriteMany, ReadOnlyMany
  hostPath: ""
  persistenceVolumeRetainPolicy: Retain 