apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: 
  name: developer-role
  namespace: development
rules: 
  - apiGroups: [""]
    resources: 
       - service
    verbs: ["*"] 

--- 
apiVersion: rbac.authorization.k8s.io/v1 
kind: RoleBinding
metadata:
  name: developer-rolebinding
  namespace: development
subjects:
  - kind: User
    name: martin
    apiGroup: rbac.authorization.k8s.io
roleRef:  
    kind: Role
    name: developer-role
    apiGroup: rbac.authorization.k8s.io 
