apiVersion: v1
kind: Pod
metadata: 
    name: billing-kube-pod
    namespace: ckad-test
    labels: 
        app: billing-kube-pod-app
        type: billing-test-api-pod
spec: 
    containers: 
        - name: billing-kube-pod
          image: itlogiclab-restaurant-billing-kube:1.0.1
          imagePullPolicy: IfNotPresent
          ports: 
             - name: http
               containerPort: 20002
               protocol: TCP
          livenessProbe: 
              httpGet: 
                  path: /actuator/health
                  port: 20002
              initialDelaySeconds: 3
              periodSeconds: 3 
          readinessProbe: 
              httpGet: 
                  path: /actuator/health
                  port: 20002
              initialDelaySeconds: 3 
              periodSeconds: 3   
---
apiVersion: v1
kind: Service
metadata: 
   name: billing-service-pod-test
spec: 
   selector: 
       app: billing-kube-pod-app
   type: NodePort
   clusterIP: 10.101.102.103
   ports:
     - targetPort: 20002  ## PORT OF POD: PORT ON WHICH APP IS RUNNING
       port: 80  ## PORT OF SERVICE, DEFAULT 80. NEED TO CHECK HOW TO CHANGE IT.
       nodePort: 30010 # PORT WHERE AOO IS ACCESSIBLE:  Range: 30000 to 32767 