apiVersion: rbac.authorizaiton.k8s.io/v1
kind: Role
metadata: 
  name: ckad-role-test
rule: 
  - apiGroup: [""]
    resources: 
      - Service
      - Pod
    verb: 
      - create
      - update
      - delete 

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: 
  name: ckad-role-binding-test
subjects: 
   - kind: User
     name: minikube
     apiGroup: rbac.authorization.k8s.io
roleRef: 
    - kind: Role
      name: ckad-role-test
      apiGroup: rbac.authorization.k8s.io
   
