apiVersion: v1
kind: Service
metadata: 
   name: lab-svc
spec: 
   selector: 
     app: lab-pod-labels
   type: NodePort
   ports: 
      - targetPort: 80
        port: 8080
        nodePort: 32767
   