apiVersion: apps/v1
kind: Deployment
metadata: 
 name: lab-deploy
spec: 
   replicas: 1 
   strategy: 
      type: RollingUpdate
   selector: 
     matchLabels: 
        app: lab-pod-labels 
   template: 
     metadata: 
        name: lab-pod
        labels: 
           app: lab-pod-labels
     spec: 
        containers: 
          - name:  lab-pod-1
            image: nginx:1.23.3
            env: 
             - name: NGINX_HOST
               value: logiclab.com
             - name: NGINX_PORT
               value: "80"
            ports: 
               - name: http
                 containerPort: 20012
                 protocol: TCP    
            